global using Nerd_STF.Mathematics;
global using SrcMod.Shell;
global using SrcMod.Shell.Modules.ObjectModels;
global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.IO;
global using System.IO.Compression;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Threading;
global using static SrcMod.Shell.Tools;
